### ISSUE TITLE
with go mod echo-swagger cant find package

### ISSUE THREAD

**Issue by hZYuu** [swaggo/echo-swagger#10]
hi, 
  i have some issue that i can run go build, go test, go get
  that because go send error like this

  - go: finding github.com/swaggo/echo-swagger latest
  - go: downloading github.com/swaggo/echo-swagger v0.0.0-20190219082602-1a361fc821b8
  build myproject: cannot load github.com/swaggo/echo-swagger: cannot find module providing package github.com/swaggo/echo-swagger

  this happen when i use "go mod", anybody can help to solve this problem ?
  
  in my go mod have require like this
  
  require (
	cloud.google.com/go v0.37.1 // indirect
	github.com/PuerkitoBio/purell v1.1.1 // indirect
	github.com/denisenkom/go-mssqldb v0.0.0-20190315220205-a8ed825ac853
	github.com/gin-contrib/sse v0.0.0-20190301062529-5545eab6dad3 // indirect
	github.com/golang/protobuf v1.3.1 // indirect
	github.com/kr/pty v1.1.4 // indirect
	github.com/labstack/echo v3.3.10+incompatible
	github.com/mailru/easyjson v0.0.0-20190312143242-1de009706dbe // indirect
	github.com/mattn/go-colorable v0.1.1 // indirect
	github.com/mattn/go-isatty v0.0.7 // indirect
	github.com/mitchellh/mapstructure v1.1.2
	github.com/swaggo/echo-swagger/v2 v2.0.0-20190219082602-1a361fc821b8
	github.com/swaggo/gin-swagger v1.1.0 // indirect
	github.com/swaggo/swag v1.4.1 // indirect
	github.com/tylerb/graceful v1.2.15
	github.com/ugorji/go/codec v0.0.0-20190320090025-2dc34c0b8780 // indirect
	github.com/valyala/fasttemplate v1.0.1 // indirect
	golang.org/x/crypto v0.0.0-20190320223903-b7391e95e576 // indirect
	golang.org/x/net v0.0.0-20190322120337-addf6b3196f6 // indirect
	golang.org/x/sys v0.0.0-20190322080309-f49334f85ddc // indirect
	golang.org/x/tools v0.0.0-20190322203728-c1a832b0ad89 // indirect
  )

  thank you

**Comment by easonlin404** [comment]
It's worked for me. would you post your command and completely error message?

**Comment by hZYuu** [comment]
easonlin404

I try to use echoSwagger with function warpHandler

and import echo and swaggo like this

import (
  "github.com/labstack/echo"
  "github.com/swaggo/echo-swsgger"
)

dont have /v4 on echo path and /v2 on swaggo path

this problem come with go module
without it i can use go build or go test or any

**Comment by hZYuu** [comment]
this error can be escape if i dont use swaggo but i want to know y only this package of swaggo that go compiler cant find or get it with go module

**Comment by easonlin404** [comment]
I think this error is caused by wrong go module version. fix via https://github.com/swaggo/echo-swagger/pull/11

**Comment by hZYuu** [comment]
My go version is 1.12.1 and when i use go mod i have to type GO111MODULE=on this version of my go module can fixed ? 

:(

**Comment by easonlin404** [comment]
Will all work if `GO111MODULE `set by `on` or `auto`.

**Comment by hZYuu** [comment]
easonlin404, thank for answer my question, i will find another way to write swagger without swaggo, i dont have time too much too solve every problem but i still want to use go module for control version of package on github

thank you

👍
