### ISSUE TITLE
Expose OpenAPI in yml in a different endpoint

### ISSUE THREAD

**Issue by EdouardBavoux** [swaggo/echo-swagger#109]
Hi, 
Would be good to have the possibility to expose the .yml resource in a dedicated endpoint. (Our use case is to interface with a tool that fetches documentation and is only consuming yml). Would it be valuable for the project ? If so, I'll try to have a look and submit a pull request.
Thanks anyway for your work !
Ed

**Comment by starcharles** [comment]
I have tried to implement this feature in https://github.com/swaggo/echo-swagger/pull/111

Please check it if you have time.

**Comment by starcharles** [comment]
maybe this issue can be closed.

**Comment by EdouardBavoux** [comment]
Indeed, thank you !
