### ISSUE TITLE
Canonical example don't work

### ISSUE THREAD

**Issue by Stunext** [swaggo/echo-swagger#3]
Open http://localhost:1323/swagger/index.html just show a white page. The problem, in my case, is with this line "e.Use(middleware.Gzip())"

**Comment by Stunext** [comment]
The problem in my case is "e.Use(middleware.Gzip())"

**Comment by easonlin404** [comment]
Could you post your code?

**Comment by Stunext** [comment]
In my project I needed to use several middleware like CORS, GZIP, Logger... I have isolated the problem that I explained in my previous comment. The problem is with the Gzip middleware.

This code does not work

`package main

import (
	"github.com/labstack/echo"
	"github.com/labstack/echo/middleware"
	"github.com/swaggo/echo-swagger"
	_ "github.com/swaggo/echo-swagger/example/docs"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host petstore.swagger.io
// @BasePath /v2
func main() {
	e := echo.New()
	e.Use(middleware.Gzip())
	e.GET("/swagger/*", echoSwagger.WrapHandler)
	e.Logger.Fatal(e.Start(":3000"))
}`

I have to change the Gzip middleware to

`e.Use(middleware.GzipWithConfig(middleware.GzipConfig{
	Skipper: func(c echo.Context) bool {
		if strings.Contains(c.Path(), "swagger") {
			return true
		}
		return false
	},
}))`

**Comment by wantdrink** [comment]
@Stunext , @easonlin404  I'm using echo/v4 v4.1.13 and echo-swagger v0.0.0-20191205130555-62f81ea88919. I have the same issue: enabling GzipWithConfig middleware of echo lead to a white space for /swagger/index.html.
Disabling gzip and the page works.

Is that mean we cannot use echo's gzip middleware with echo-swagger at the same time?
Thanks.

**Comment by Stunext** [comment]
Yeah, with Gzip does not work, but you can disable gzip only for the documentation path using this code.

`e.Use (middleware.GzipWithConfig (middleware.GzipConfig {
   Skipper: func (c echo.Context) bool {
      if strings.Contains (c.Path (), "swagger") {  // Change "swagger" for your own path
         return true
      }
      return false
   },
}))`

**Comment by wantdrink** [comment]
Thanks @Stunext !
