### ISSUE TITLE
Register called twice for swag

### ISSUE THREAD

**Issue by knarukulla** [swaggo/echo-swagger#32]
I have two webserver starting in same main program. If i try to register them as separate swagger module, its throwing following error.

panic: Register called twice for swag: Management

goroutine 1 [running]:
github.com/swaggo/swag.Register(0x18ce987, 0xa, 0x19b23e0, 0x2716df0)
        /Users/knarukulla/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/swaggo/swag@v1.6.7/swagger.go:30 +0x12f
identity/web/mgmt/docs.init.0()
        /Users/knarukulla/workspace/data-processing/src/main/go/src/identity/web/mgmt/docs/docs.go:487 +0x

**Comment by ubogdan** [comment]
Unfortunately, this is not possible with the current version of swag. See [#949](https://github.com/swaggo/swag/issues/949) as example.

**Comment by eduardo-mior** [comment]
I have the same problem.
I have internal documentation for my team and I have public documentation for other companies to consume. How can I solve?

**Comment by ubogdan** [comment]
Please stop flooding. 1st warning.
