### ISSUE TITLE
Swagger doesn't update HTML

### ISSUE THREAD

**Issue by burredis** [swaggo/echo-swagger#40]
I don't know how, but the doc.json seem to be static. I run the `$ swagger init --g main.go`, all files are created/edited and when I access by browser /swagger/index.html, nothing happens, doesn't update the JSON

```go
// FIX TO LOAD CORRECT FILE
e.File("/swagger/doc.json", "./docs/swagger.json")
```

Libs and  versions
v4.2.1 - github.com/labstack/echo/v4
v1.1.0 - github.com/swaggo/echo-swagger
v1.7.0 - github.com/swaggo/swag

**Comment by ubogdan** [comment]
You need to import the generated package docs package into your code [see](https://github.com/swaggo/echo-swagger#canonical-example). Optionally you can carefully read the documentation.

```
package main

import (
	"github.com/labstack/echo/v4"
	"github.com/swaggo/echo-swagger"

	_ "github.com/user/project/path_to_generated_swagger/docs" 
)
```

**Comment by burredis** [comment]
I followed all steps to use the lib. All imports, everything that is written at the doc. I think that have something wrong when generate the HTML files after run `$ swagger init --g main.go`, because the path of docs.json doesn't change.
