### ISSUE TITLE
Is it possible to create swagger-ui from a yaml file

### ISSUE THREAD

**Issue by delgec** [swaggo/echo-swagger#79]
Hello everyone

I'm trying to create swagger ui from a yaml file but I getting an error.

I could not solve this problem.

How can I make it?

Help me please.
Thanks

```
e := echo.New()

url := echoSwagger.URL("./static/openapi.yaml")
e.GET("/swagger/*", echoSwagger.EchoWrapHandler(url))

e.Logger.Fatal(e.Start(":1919"))
```

**Output Screenshot:**

![Screenshot from 2022-02-23 12-28-21](https://user-images.githubusercontent.com/61455673/155292220-72debeb9-d40e-4756-a953-79b3606c5119.png)

**Comment by ubogdan** [comment]
It's possible but you need to serve that via a static file handler. By default the swag.json and swag.yaml generated files are simply garbage. The docs.go code contains an embedded copy of the swag.json.
